# theme: jekyll-theme-minimal
# remote_theme: "jekyll/minima@2.5-stable"

theme: just-the-docs

# Note, we are using version 2.5, so you shoudl 
# read these instuctions, not the ones at the HEAD of the
# master branch
# https://github.com/jekyll/minima/blob/2.5-stable/README.md

title: Hour of Microbit

description: >
  Introduction to the BBC Micro:bit, an amazing, tiny computer that you can program!
  Learn programming, robotics, and how to create games with friends.


author:
  name: Andy M. Azing
  email: "student@jointheleague.org"

plugins:
  - jekyll-remote-theme
  - jekyll-default-layout

header_pages:
  - about.md
  - intro.md
  - lessons/index.md






