base: /HourofMicrobit/
description: Hour of Microbit
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /intro
    title: Introduction
  - children:
    - path: /lessons/get_started/setup/
      title: Getting Started
    collapsable: false
    title: Getting Started
  - children:
    - path: /lessons/lesson1/first_projects/
      title: First Projects
    - path: /lessons/lesson1/moreprojects/
      title: More Projects
    collapsable: false
    title: First Projects
  - children:
    - path: /lessons/cutebot/setup/
      title: Setup your Cutebot
    - path: /lessons/cutebot/square/
      title: Make A Square
    - path: /lessons/cutebot/sonar/
      title: Open Your Eyes BatBot
    - path: /lessons/cutebot/moreprojects/
      title: More Projects
    collapsable: false
    path: /lessons/cutebot/
    title: Cutebot
  - children:
    - path: /lessons/arcade/bunnyhop/
      title: Play Bunny Hop
    - path: /lessons/arcade/setup/
      title: Setup Your Arcade
    - path: /lessons/arcade/tutorials/
      title: Try The Tutorials
    - path: /lessons/arcade/eatfruit/
      title: Eat the Fruit
    - path: /lessons/arcade/modify_flappy/
      title: Easier Flapping
    - path: /lessons/arcade/asteroids/
      title: Asteroids
    - path: /lessons/arcade/makeyourown/
      title: Make Your Own Game
    collapsable: false
    path: /lessons/arcade/
    title: Arcade Games
title: Hour of Microbit
